In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [3]:
data = pd.read_csv("./datasets/boston.csv")

x = np.array(data['RM'])
y = np.array(data['MV'])


In [4]:
fig = px.scatter(x= x, y=y)
fig.show()

In [5]:
# Column of 1s for intercept
ones = np.ones(x.shape[0]).reshape(x.shape[0], 1)

# Identity Matrix
X = x.reshape(x.shape[0], 1)
X = np.concatenate((ones, X), axis = 1)

# Identity matrix transposed
XT = X.T

# Dot product of transposed identity matrix and the identity matrix
XTX = np.dot(XT, X)

# Inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# Dot product of transposed identity matrix and y
XTy = np.dot(XT,y)

# Dot product of inversed XTX and XTy
beta_hat = np.dot(XTX_inv, XTy)

In [6]:
beta_hat

array([-34.67062078,   9.10210898])

In [7]:
yhat = X.dot(beta_hat)

In [8]:
fig1 = px.scatter(x=x, y=y)

fig2 = px.line(x=x, y=yhat)
fig2['data'][0]['line']['color']="red"

fig3 = go.Figure(data=fig1.data + fig2.data)
fig3.show()

In [9]:
data

x = data
y = np.array(data['MV'])

In [10]:
x = np.array(data.iloc[: , 1:])

In [15]:
x


array([[  2.31 ,  53.8  ,   6.575, 296.   ,  15.3  ,   4.98 ],
       [  7.07 ,  46.9  ,   6.421, 242.   ,  17.8  ,   9.14 ],
       [  7.07 ,  46.9  ,   7.185, 242.   ,  17.8  ,   4.03 ],
       ...,
       [ 11.93 ,  57.3  ,   6.976, 273.   ,  21.   ,   5.64 ],
       [ 11.93 ,  57.3  ,   6.794, 273.   ,  21.   ,   6.48 ],
       [ 11.93 ,  57.3  ,   6.03 , 273.   ,  21.   ,   7.88 ]])

In [16]:
# Column of 1s for intercept
ones = np.ones(x.shape[0]).reshape(x.shape[0], 1)

# Identity Matrix
X = x.reshape(x.shape[0], x.shape[1])
X = np.concatenate((ones, X), axis = 1)

# Identity matrix transposed
XT = X.T

# Dot product of transposed identity matrix and the identity matrix
XTX = np.dot(XT, X)

# Inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# Dot product of transposed identity matrix and y
XTy = np.dot(XT,y)

# Dot product of inversed XTX and XTy
beta_hat = np.dot(XTX_inv, XTy)

In [17]:
beta_hat

array([ 1.91458185e+01,  8.71873392e-02, -3.40311735e-02,  4.65592779e+00,
       -2.90110504e-03, -9.13819473e-01, -5.45934588e-01])

In [18]:
yhat = X.dot(beta_hat)

In [21]:
x = np.array(data['RM'])

In [22]:
fig1 = px.scatter(x=x, y=y)

fig2 = px.line(x=x, y=yhat)
fig2['data'][0]['line']['color']="red"

fig3 = go.Figure(data=fig1.data + fig2.data)
fig3.show()